apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stuart-bot-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-stuart-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: stuart-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        key: BOT_TOKEN
    - secretKey: DISCORD_GUILD_ID
      remoteRef:
        key: DISCORD_GUILD_ID
