apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-secret.yaml

namespace: stuart

labels:
  - pairs:
      environment: prod
      app.kubernetes.io/environment: prod

patches:
  - path: deployment.patch.yaml
