apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: pk-bkd-bot-stuart
  app.kubernetes.io/part-of: pk-bkd-bot-stuart
